// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cloud_read.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct PlaydenCloud_CCloud_ClientFileDownload_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var appid: UInt32 {
    get {_appid ?? 0}
    set {_appid = newValue}
  }
  /// Returns true if `appid` has been explicitly set.
  public var hasAppid: Bool {self._appid != nil}
  /// Clears the value of `appid`. Subsequent reads from it will return its default value.
  public mutating func clearAppid() {self._appid = nil}

  public var filename: String {
    get {_filename ?? String()}
    set {_filename = newValue}
  }
  /// Returns true if `filename` has been explicitly set.
  public var hasFilename: Bool {self._filename != nil}
  /// Clears the value of `filename`. Subsequent reads from it will return its default value.
  public mutating func clearFilename() {self._filename = nil}

  public var realm: UInt32 {
    get {_realm ?? 0}
    set {_realm = newValue}
  }
  /// Returns true if `realm` has been explicitly set.
  public var hasRealm: Bool {self._realm != nil}
  /// Clears the value of `realm`. Subsequent reads from it will return its default value.
  public mutating func clearRealm() {self._realm = nil}

  public var forceProxy: Bool {
    get {_forceProxy ?? false}
    set {_forceProxy = newValue}
  }
  /// Returns true if `forceProxy` has been explicitly set.
  public var hasForceProxy: Bool {self._forceProxy != nil}
  /// Clears the value of `forceProxy`. Subsequent reads from it will return its default value.
  public mutating func clearForceProxy() {self._forceProxy = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _appid: UInt32? = nil
  fileprivate var _filename: String? = nil
  fileprivate var _realm: UInt32? = nil
  fileprivate var _forceProxy: Bool? = nil
}

public nonisolated struct PlaydenCloud_CCloud_ClientFileDownload_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var appid: UInt32 {
    get {_appid ?? 0}
    set {_appid = newValue}
  }
  /// Returns true if `appid` has been explicitly set.
  public var hasAppid: Bool {self._appid != nil}
  /// Clears the value of `appid`. Subsequent reads from it will return its default value.
  public mutating func clearAppid() {self._appid = nil}

  public var fileSize: UInt32 {
    get {_fileSize ?? 0}
    set {_fileSize = newValue}
  }
  /// Returns true if `fileSize` has been explicitly set.
  public var hasFileSize: Bool {self._fileSize != nil}
  /// Clears the value of `fileSize`. Subsequent reads from it will return its default value.
  public mutating func clearFileSize() {self._fileSize = nil}

  public var rawFileSize: UInt32 {
    get {_rawFileSize ?? 0}
    set {_rawFileSize = newValue}
  }
  /// Returns true if `rawFileSize` has been explicitly set.
  public var hasRawFileSize: Bool {self._rawFileSize != nil}
  /// Clears the value of `rawFileSize`. Subsequent reads from it will return its default value.
  public mutating func clearRawFileSize() {self._rawFileSize = nil}

  public var shaFile: Data {
    get {_shaFile ?? Data()}
    set {_shaFile = newValue}
  }
  /// Returns true if `shaFile` has been explicitly set.
  public var hasShaFile: Bool {self._shaFile != nil}
  /// Clears the value of `shaFile`. Subsequent reads from it will return its default value.
  public mutating func clearShaFile() {self._shaFile = nil}

  public var timeStamp: UInt64 {
    get {_timeStamp ?? 0}
    set {_timeStamp = newValue}
  }
  /// Returns true if `timeStamp` has been explicitly set.
  public var hasTimeStamp: Bool {self._timeStamp != nil}
  /// Clears the value of `timeStamp`. Subsequent reads from it will return its default value.
  public mutating func clearTimeStamp() {self._timeStamp = nil}

  public var isExplicitDelete: Bool {
    get {_isExplicitDelete ?? false}
    set {_isExplicitDelete = newValue}
  }
  /// Returns true if `isExplicitDelete` has been explicitly set.
  public var hasIsExplicitDelete: Bool {self._isExplicitDelete != nil}
  /// Clears the value of `isExplicitDelete`. Subsequent reads from it will return its default value.
  public mutating func clearIsExplicitDelete() {self._isExplicitDelete = nil}

  public var urlHost: String {
    get {_urlHost ?? String()}
    set {_urlHost = newValue}
  }
  /// Returns true if `urlHost` has been explicitly set.
  public var hasURLHost: Bool {self._urlHost != nil}
  /// Clears the value of `urlHost`. Subsequent reads from it will return its default value.
  public mutating func clearURLHost() {self._urlHost = nil}

  public var urlPath: String {
    get {_urlPath ?? String()}
    set {_urlPath = newValue}
  }
  /// Returns true if `urlPath` has been explicitly set.
  public var hasURLPath: Bool {self._urlPath != nil}
  /// Clears the value of `urlPath`. Subsequent reads from it will return its default value.
  public mutating func clearURLPath() {self._urlPath = nil}

  public var useHTTPS: Bool {
    get {_useHTTPS ?? false}
    set {_useHTTPS = newValue}
  }
  /// Returns true if `useHTTPS` has been explicitly set.
  public var hasUseHTTPS: Bool {self._useHTTPS != nil}
  /// Clears the value of `useHTTPS`. Subsequent reads from it will return its default value.
  public mutating func clearUseHTTPS() {self._useHTTPS = nil}

  public var requestHeaders: [PlaydenCloud_CCloud_ClientFileDownload_Response.HTTPHeaders] = []

  public var encrypted: Bool {
    get {_encrypted ?? false}
    set {_encrypted = newValue}
  }
  /// Returns true if `encrypted` has been explicitly set.
  public var hasEncrypted: Bool {self._encrypted != nil}
  /// Clears the value of `encrypted`. Subsequent reads from it will return its default value.
  public mutating func clearEncrypted() {self._encrypted = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated struct HTTPHeaders: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var name: String {
      get {_name ?? String()}
      set {_name = newValue}
    }
    /// Returns true if `name` has been explicitly set.
    public var hasName: Bool {self._name != nil}
    /// Clears the value of `name`. Subsequent reads from it will return its default value.
    public mutating func clearName() {self._name = nil}

    public var value: String {
      get {_value ?? String()}
      set {_value = newValue}
    }
    /// Returns true if `value` has been explicitly set.
    public var hasValue: Bool {self._value != nil}
    /// Clears the value of `value`. Subsequent reads from it will return its default value.
    public mutating func clearValue() {self._value = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _name: String? = nil
    fileprivate var _value: String? = nil
  }

  public init() {}

  fileprivate var _appid: UInt32? = nil
  fileprivate var _fileSize: UInt32? = nil
  fileprivate var _rawFileSize: UInt32? = nil
  fileprivate var _shaFile: Data? = nil
  fileprivate var _timeStamp: UInt64? = nil
  fileprivate var _isExplicitDelete: Bool? = nil
  fileprivate var _urlHost: String? = nil
  fileprivate var _urlPath: String? = nil
  fileprivate var _useHTTPS: Bool? = nil
  fileprivate var _encrypted: Bool? = nil
}

public nonisolated struct PlaydenCloud_CCloud_GetAppFileChangelist_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var appid: UInt32 {
    get {_appid ?? 0}
    set {_appid = newValue}
  }
  /// Returns true if `appid` has been explicitly set.
  public var hasAppid: Bool {self._appid != nil}
  /// Clears the value of `appid`. Subsequent reads from it will return its default value.
  public mutating func clearAppid() {self._appid = nil}

  public var syncedChangeNumber: UInt64 {
    get {_syncedChangeNumber ?? 0}
    set {_syncedChangeNumber = newValue}
  }
  /// Returns true if `syncedChangeNumber` has been explicitly set.
  public var hasSyncedChangeNumber: Bool {self._syncedChangeNumber != nil}
  /// Clears the value of `syncedChangeNumber`. Subsequent reads from it will return its default value.
  public mutating func clearSyncedChangeNumber() {self._syncedChangeNumber = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _appid: UInt32? = nil
  fileprivate var _syncedChangeNumber: UInt64? = nil
}

public nonisolated struct PlaydenCloud_CCloud_GetAppFileChangelist_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var currentChangeNumber: UInt64 {
    get {_currentChangeNumber ?? 0}
    set {_currentChangeNumber = newValue}
  }
  /// Returns true if `currentChangeNumber` has been explicitly set.
  public var hasCurrentChangeNumber: Bool {self._currentChangeNumber != nil}
  /// Clears the value of `currentChangeNumber`. Subsequent reads from it will return its default value.
  public mutating func clearCurrentChangeNumber() {self._currentChangeNumber = nil}

  public var files: [PlaydenCloud_CCloud_AppFileInfo] = []

  public var isOnlyDelta: Bool {
    get {_isOnlyDelta ?? false}
    set {_isOnlyDelta = newValue}
  }
  /// Returns true if `isOnlyDelta` has been explicitly set.
  public var hasIsOnlyDelta: Bool {self._isOnlyDelta != nil}
  /// Clears the value of `isOnlyDelta`. Subsequent reads from it will return its default value.
  public mutating func clearIsOnlyDelta() {self._isOnlyDelta = nil}

  public var pathPrefixes: [String] = []

  public var machineNames: [String] = []

  public var appBuildidHwm: UInt64 {
    get {_appBuildidHwm ?? 0}
    set {_appBuildidHwm = newValue}
  }
  /// Returns true if `appBuildidHwm` has been explicitly set.
  public var hasAppBuildidHwm: Bool {self._appBuildidHwm != nil}
  /// Clears the value of `appBuildidHwm`. Subsequent reads from it will return its default value.
  public mutating func clearAppBuildidHwm() {self._appBuildidHwm = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _currentChangeNumber: UInt64? = nil
  fileprivate var _isOnlyDelta: Bool? = nil
  fileprivate var _appBuildidHwm: UInt64? = nil
}

public nonisolated struct PlaydenCloud_CCloud_AppFileInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var fileName: String {
    get {_fileName ?? String()}
    set {_fileName = newValue}
  }
  /// Returns true if `fileName` has been explicitly set.
  public var hasFileName: Bool {self._fileName != nil}
  /// Clears the value of `fileName`. Subsequent reads from it will return its default value.
  public mutating func clearFileName() {self._fileName = nil}

  public var shaFile: Data {
    get {_shaFile ?? Data()}
    set {_shaFile = newValue}
  }
  /// Returns true if `shaFile` has been explicitly set.
  public var hasShaFile: Bool {self._shaFile != nil}
  /// Clears the value of `shaFile`. Subsequent reads from it will return its default value.
  public mutating func clearShaFile() {self._shaFile = nil}

  public var timeStamp: UInt64 {
    get {_timeStamp ?? 0}
    set {_timeStamp = newValue}
  }
  /// Returns true if `timeStamp` has been explicitly set.
  public var hasTimeStamp: Bool {self._timeStamp != nil}
  /// Clears the value of `timeStamp`. Subsequent reads from it will return its default value.
  public mutating func clearTimeStamp() {self._timeStamp = nil}

  public var rawFileSize: UInt32 {
    get {_rawFileSize ?? 0}
    set {_rawFileSize = newValue}
  }
  /// Returns true if `rawFileSize` has been explicitly set.
  public var hasRawFileSize: Bool {self._rawFileSize != nil}
  /// Clears the value of `rawFileSize`. Subsequent reads from it will return its default value.
  public mutating func clearRawFileSize() {self._rawFileSize = nil}

  public var persistState: Int32 {
    get {_persistState ?? 0}
    set {_persistState = newValue}
  }
  /// Returns true if `persistState` has been explicitly set.
  public var hasPersistState: Bool {self._persistState != nil}
  /// Clears the value of `persistState`. Subsequent reads from it will return its default value.
  public mutating func clearPersistState() {self._persistState = nil}

  public var platformsToSync: UInt32 {
    get {_platformsToSync ?? 0}
    set {_platformsToSync = newValue}
  }
  /// Returns true if `platformsToSync` has been explicitly set.
  public var hasPlatformsToSync: Bool {self._platformsToSync != nil}
  /// Clears the value of `platformsToSync`. Subsequent reads from it will return its default value.
  public mutating func clearPlatformsToSync() {self._platformsToSync = nil}

  public var pathPrefixIndex: UInt32 {
    get {_pathPrefixIndex ?? 0}
    set {_pathPrefixIndex = newValue}
  }
  /// Returns true if `pathPrefixIndex` has been explicitly set.
  public var hasPathPrefixIndex: Bool {self._pathPrefixIndex != nil}
  /// Clears the value of `pathPrefixIndex`. Subsequent reads from it will return its default value.
  public mutating func clearPathPrefixIndex() {self._pathPrefixIndex = nil}

  public var machineNameIndex: UInt32 {
    get {_machineNameIndex ?? 0}
    set {_machineNameIndex = newValue}
  }
  /// Returns true if `machineNameIndex` has been explicitly set.
  public var hasMachineNameIndex: Bool {self._machineNameIndex != nil}
  /// Clears the value of `machineNameIndex`. Subsequent reads from it will return its default value.
  public mutating func clearMachineNameIndex() {self._machineNameIndex = nil}

  public var reuploadRequested: Bool {
    get {_reuploadRequested ?? false}
    set {_reuploadRequested = newValue}
  }
  /// Returns true if `reuploadRequested` has been explicitly set.
  public var hasReuploadRequested: Bool {self._reuploadRequested != nil}
  /// Clears the value of `reuploadRequested`. Subsequent reads from it will return its default value.
  public mutating func clearReuploadRequested() {self._reuploadRequested = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _fileName: String? = nil
  fileprivate var _shaFile: Data? = nil
  fileprivate var _timeStamp: UInt64? = nil
  fileprivate var _rawFileSize: UInt32? = nil
  fileprivate var _persistState: Int32? = nil
  fileprivate var _platformsToSync: UInt32? = nil
  fileprivate var _pathPrefixIndex: UInt32? = nil
  fileprivate var _machineNameIndex: UInt32? = nil
  fileprivate var _reuploadRequested: Bool? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "PlaydenCloud"

nonisolated extension PlaydenCloud_CCloud_ClientFileDownload_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_ClientFileDownload_Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}appid\0\u{1}filename\0\u{1}realm\0\u{3}force_proxy\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._appid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._filename) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self._realm) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self._forceProxy) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._appid {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._filename {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._realm {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._forceProxy {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_ClientFileDownload_Request, rhs: PlaydenCloud_CCloud_ClientFileDownload_Request) -> Bool {
    if lhs._appid != rhs._appid {return false}
    if lhs._filename != rhs._filename {return false}
    if lhs._realm != rhs._realm {return false}
    if lhs._forceProxy != rhs._forceProxy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_ClientFileDownload_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_ClientFileDownload_Response"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}appid\0\u{3}file_size\0\u{3}raw_file_size\0\u{3}sha_file\0\u{3}time_stamp\0\u{3}is_explicit_delete\0\u{3}url_host\0\u{3}url_path\0\u{3}use_https\0\u{3}request_headers\0\u{1}encrypted\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._appid) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._fileSize) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self._rawFileSize) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self._shaFile) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self._timeStamp) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._isExplicitDelete) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._urlHost) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._urlPath) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self._useHTTPS) }()
      case 10: try { try decoder.decodeRepeatedMessageField(value: &self.requestHeaders) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self._encrypted) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._appid {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._fileSize {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._rawFileSize {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._shaFile {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._timeStamp {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._isExplicitDelete {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._urlHost {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._urlPath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._useHTTPS {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
    } }()
    if !self.requestHeaders.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.requestHeaders, fieldNumber: 10)
    }
    try { if let v = self._encrypted {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 11)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_ClientFileDownload_Response, rhs: PlaydenCloud_CCloud_ClientFileDownload_Response) -> Bool {
    if lhs._appid != rhs._appid {return false}
    if lhs._fileSize != rhs._fileSize {return false}
    if lhs._rawFileSize != rhs._rawFileSize {return false}
    if lhs._shaFile != rhs._shaFile {return false}
    if lhs._timeStamp != rhs._timeStamp {return false}
    if lhs._isExplicitDelete != rhs._isExplicitDelete {return false}
    if lhs._urlHost != rhs._urlHost {return false}
    if lhs._urlPath != rhs._urlPath {return false}
    if lhs._useHTTPS != rhs._useHTTPS {return false}
    if lhs.requestHeaders != rhs.requestHeaders {return false}
    if lhs._encrypted != rhs._encrypted {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_ClientFileDownload_Response.HTTPHeaders: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = PlaydenCloud_CCloud_ClientFileDownload_Response.protoMessageName + ".HTTPHeaders"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}value\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._value) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._value {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_ClientFileDownload_Response.HTTPHeaders, rhs: PlaydenCloud_CCloud_ClientFileDownload_Response.HTTPHeaders) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._value != rhs._value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_GetAppFileChangelist_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_GetAppFileChangelist_Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}appid\0\u{3}synced_change_number\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._appid) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self._syncedChangeNumber) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._appid {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._syncedChangeNumber {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_GetAppFileChangelist_Request, rhs: PlaydenCloud_CCloud_GetAppFileChangelist_Request) -> Bool {
    if lhs._appid != rhs._appid {return false}
    if lhs._syncedChangeNumber != rhs._syncedChangeNumber {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_GetAppFileChangelist_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_GetAppFileChangelist_Response"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}current_change_number\0\u{1}files\0\u{3}is_only_delta\0\u{3}path_prefixes\0\u{3}machine_names\0\u{3}app_buildid_hwm\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self._currentChangeNumber) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.files) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._isOnlyDelta) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.pathPrefixes) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.machineNames) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self._appBuildidHwm) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._currentChangeNumber {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 1)
    } }()
    if !self.files.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.files, fieldNumber: 2)
    }
    try { if let v = self._isOnlyDelta {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    if !self.pathPrefixes.isEmpty {
      try visitor.visitRepeatedStringField(value: self.pathPrefixes, fieldNumber: 4)
    }
    if !self.machineNames.isEmpty {
      try visitor.visitRepeatedStringField(value: self.machineNames, fieldNumber: 5)
    }
    try { if let v = self._appBuildidHwm {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_GetAppFileChangelist_Response, rhs: PlaydenCloud_CCloud_GetAppFileChangelist_Response) -> Bool {
    if lhs._currentChangeNumber != rhs._currentChangeNumber {return false}
    if lhs.files != rhs.files {return false}
    if lhs._isOnlyDelta != rhs._isOnlyDelta {return false}
    if lhs.pathPrefixes != rhs.pathPrefixes {return false}
    if lhs.machineNames != rhs.machineNames {return false}
    if lhs._appBuildidHwm != rhs._appBuildidHwm {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_AppFileInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_AppFileInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}file_name\0\u{3}sha_file\0\u{3}time_stamp\0\u{3}raw_file_size\0\u{3}persist_state\0\u{3}platforms_to_sync\0\u{3}path_prefix_index\0\u{3}machine_name_index\0\u{3}reupload_requested\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._fileName) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self._shaFile) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self._timeStamp) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self._rawFileSize) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._persistState) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self._platformsToSync) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self._pathPrefixIndex) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self._machineNameIndex) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self._reuploadRequested) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._fileName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._shaFile {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._timeStamp {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._rawFileSize {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._persistState {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._platformsToSync {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._pathPrefixIndex {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._machineNameIndex {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._reuploadRequested {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_AppFileInfo, rhs: PlaydenCloud_CCloud_AppFileInfo) -> Bool {
    if lhs._fileName != rhs._fileName {return false}
    if lhs._shaFile != rhs._shaFile {return false}
    if lhs._timeStamp != rhs._timeStamp {return false}
    if lhs._rawFileSize != rhs._rawFileSize {return false}
    if lhs._persistState != rhs._persistState {return false}
    if lhs._platformsToSync != rhs._platformsToSync {return false}
    if lhs._pathPrefixIndex != rhs._pathPrefixIndex {return false}
    if lhs._machineNameIndex != rhs._machineNameIndex {return false}
    if lhs._reuploadRequested != rhs._reuploadRequested {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
