// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cloud_write.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct PlaydenCloud_CCloud_BeginAppUploadBatch_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var appid: UInt32 {
    get {_appid ?? 0}
    set {_appid = newValue}
  }
  /// Returns true if `appid` has been explicitly set.
  public var hasAppid: Bool {self._appid != nil}
  /// Clears the value of `appid`. Subsequent reads from it will return its default value.
  public mutating func clearAppid() {self._appid = nil}

  public var machineName: String {
    get {_machineName ?? String()}
    set {_machineName = newValue}
  }
  /// Returns true if `machineName` has been explicitly set.
  public var hasMachineName: Bool {self._machineName != nil}
  /// Clears the value of `machineName`. Subsequent reads from it will return its default value.
  public mutating func clearMachineName() {self._machineName = nil}

  public var filesToUpload: [String] = []

  public var filesToDelete: [String] = []

  public var clientID: UInt64 {
    get {_clientID ?? 0}
    set {_clientID = newValue}
  }
  /// Returns true if `clientID` has been explicitly set.
  public var hasClientID: Bool {self._clientID != nil}
  /// Clears the value of `clientID`. Subsequent reads from it will return its default value.
  public mutating func clearClientID() {self._clientID = nil}

  public var appBuildID: UInt64 {
    get {_appBuildID ?? 0}
    set {_appBuildID = newValue}
  }
  /// Returns true if `appBuildID` has been explicitly set.
  public var hasAppBuildID: Bool {self._appBuildID != nil}
  /// Clears the value of `appBuildID`. Subsequent reads from it will return its default value.
  public mutating func clearAppBuildID() {self._appBuildID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _appid: UInt32? = nil
  fileprivate var _machineName: String? = nil
  fileprivate var _clientID: UInt64? = nil
  fileprivate var _appBuildID: UInt64? = nil
}

public nonisolated struct PlaydenCloud_CCloud_BeginAppUploadBatch_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var batchID: UInt64 {
    get {_batchID ?? 0}
    set {_batchID = newValue}
  }
  /// Returns true if `batchID` has been explicitly set.
  public var hasBatchID: Bool {self._batchID != nil}
  /// Clears the value of `batchID`. Subsequent reads from it will return its default value.
  public mutating func clearBatchID() {self._batchID = nil}

  public var appChangeNumber: UInt64 {
    get {_appChangeNumber ?? 0}
    set {_appChangeNumber = newValue}
  }
  /// Returns true if `appChangeNumber` has been explicitly set.
  public var hasAppChangeNumber: Bool {self._appChangeNumber != nil}
  /// Clears the value of `appChangeNumber`. Subsequent reads from it will return its default value.
  public mutating func clearAppChangeNumber() {self._appChangeNumber = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _batchID: UInt64? = nil
  fileprivate var _appChangeNumber: UInt64? = nil
}

public nonisolated struct PlaydenCloud_CCloud_CompleteAppUploadBatch_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var appid: UInt32 {
    get {_appid ?? 0}
    set {_appid = newValue}
  }
  /// Returns true if `appid` has been explicitly set.
  public var hasAppid: Bool {self._appid != nil}
  /// Clears the value of `appid`. Subsequent reads from it will return its default value.
  public mutating func clearAppid() {self._appid = nil}

  public var batchID: UInt64 {
    get {_batchID ?? 0}
    set {_batchID = newValue}
  }
  /// Returns true if `batchID` has been explicitly set.
  public var hasBatchID: Bool {self._batchID != nil}
  /// Clears the value of `batchID`. Subsequent reads from it will return its default value.
  public mutating func clearBatchID() {self._batchID = nil}

  public var batchEresult: UInt32 {
    get {_batchEresult ?? 0}
    set {_batchEresult = newValue}
  }
  /// Returns true if `batchEresult` has been explicitly set.
  public var hasBatchEresult: Bool {self._batchEresult != nil}
  /// Clears the value of `batchEresult`. Subsequent reads from it will return its default value.
  public mutating func clearBatchEresult() {self._batchEresult = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _appid: UInt32? = nil
  fileprivate var _batchID: UInt64? = nil
  fileprivate var _batchEresult: UInt32? = nil
}

public nonisolated struct PlaydenCloud_CCloud_CompleteAppUploadBatch_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct PlaydenCloud_CCloud_ClientBeginFileUpload_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var appid: UInt32 {
    get {_appid ?? 0}
    set {_appid = newValue}
  }
  /// Returns true if `appid` has been explicitly set.
  public var hasAppid: Bool {self._appid != nil}
  /// Clears the value of `appid`. Subsequent reads from it will return its default value.
  public mutating func clearAppid() {self._appid = nil}

  public var fileSize: UInt32 {
    get {_fileSize ?? 0}
    set {_fileSize = newValue}
  }
  /// Returns true if `fileSize` has been explicitly set.
  public var hasFileSize: Bool {self._fileSize != nil}
  /// Clears the value of `fileSize`. Subsequent reads from it will return its default value.
  public mutating func clearFileSize() {self._fileSize = nil}

  public var rawFileSize: UInt32 {
    get {_rawFileSize ?? 0}
    set {_rawFileSize = newValue}
  }
  /// Returns true if `rawFileSize` has been explicitly set.
  public var hasRawFileSize: Bool {self._rawFileSize != nil}
  /// Clears the value of `rawFileSize`. Subsequent reads from it will return its default value.
  public mutating func clearRawFileSize() {self._rawFileSize = nil}

  public var fileSha: Data {
    get {_fileSha ?? Data()}
    set {_fileSha = newValue}
  }
  /// Returns true if `fileSha` has been explicitly set.
  public var hasFileSha: Bool {self._fileSha != nil}
  /// Clears the value of `fileSha`. Subsequent reads from it will return its default value.
  public mutating func clearFileSha() {self._fileSha = nil}

  public var timeStamp: UInt64 {
    get {_timeStamp ?? 0}
    set {_timeStamp = newValue}
  }
  /// Returns true if `timeStamp` has been explicitly set.
  public var hasTimeStamp: Bool {self._timeStamp != nil}
  /// Clears the value of `timeStamp`. Subsequent reads from it will return its default value.
  public mutating func clearTimeStamp() {self._timeStamp = nil}

  public var filename: String {
    get {_filename ?? String()}
    set {_filename = newValue}
  }
  /// Returns true if `filename` has been explicitly set.
  public var hasFilename: Bool {self._filename != nil}
  /// Clears the value of `filename`. Subsequent reads from it will return its default value.
  public mutating func clearFilename() {self._filename = nil}

  public var platformsToSync: UInt32 {
    get {_platformsToSync ?? 4294967295}
    set {_platformsToSync = newValue}
  }
  /// Returns true if `platformsToSync` has been explicitly set.
  public var hasPlatformsToSync: Bool {self._platformsToSync != nil}
  /// Clears the value of `platformsToSync`. Subsequent reads from it will return its default value.
  public mutating func clearPlatformsToSync() {self._platformsToSync = nil}

  public var cellID: UInt32 {
    get {_cellID ?? 0}
    set {_cellID = newValue}
  }
  /// Returns true if `cellID` has been explicitly set.
  public var hasCellID: Bool {self._cellID != nil}
  /// Clears the value of `cellID`. Subsequent reads from it will return its default value.
  public mutating func clearCellID() {self._cellID = nil}

  public var canEncrypt: Bool {
    get {_canEncrypt ?? false}
    set {_canEncrypt = newValue}
  }
  /// Returns true if `canEncrypt` has been explicitly set.
  public var hasCanEncrypt: Bool {self._canEncrypt != nil}
  /// Clears the value of `canEncrypt`. Subsequent reads from it will return its default value.
  public mutating func clearCanEncrypt() {self._canEncrypt = nil}

  public var isSharedFile: Bool {
    get {_isSharedFile ?? false}
    set {_isSharedFile = newValue}
  }
  /// Returns true if `isSharedFile` has been explicitly set.
  public var hasIsSharedFile: Bool {self._isSharedFile != nil}
  /// Clears the value of `isSharedFile`. Subsequent reads from it will return its default value.
  public mutating func clearIsSharedFile() {self._isSharedFile = nil}

  public var deprecatedRealm: UInt32 {
    get {_deprecatedRealm ?? 0}
    set {_deprecatedRealm = newValue}
  }
  /// Returns true if `deprecatedRealm` has been explicitly set.
  public var hasDeprecatedRealm: Bool {self._deprecatedRealm != nil}
  /// Clears the value of `deprecatedRealm`. Subsequent reads from it will return its default value.
  public mutating func clearDeprecatedRealm() {self._deprecatedRealm = nil}

  public var uploadBatchID: UInt64 {
    get {_uploadBatchID ?? 0}
    set {_uploadBatchID = newValue}
  }
  /// Returns true if `uploadBatchID` has been explicitly set.
  public var hasUploadBatchID: Bool {self._uploadBatchID != nil}
  /// Clears the value of `uploadBatchID`. Subsequent reads from it will return its default value.
  public mutating func clearUploadBatchID() {self._uploadBatchID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _appid: UInt32? = nil
  fileprivate var _fileSize: UInt32? = nil
  fileprivate var _rawFileSize: UInt32? = nil
  fileprivate var _fileSha: Data? = nil
  fileprivate var _timeStamp: UInt64? = nil
  fileprivate var _filename: String? = nil
  fileprivate var _platformsToSync: UInt32? = nil
  fileprivate var _cellID: UInt32? = nil
  fileprivate var _canEncrypt: Bool? = nil
  fileprivate var _isSharedFile: Bool? = nil
  fileprivate var _deprecatedRealm: UInt32? = nil
  fileprivate var _uploadBatchID: UInt64? = nil
}

public nonisolated struct PlaydenCloud_ClientCloudFileUploadBlockDetails: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var urlHost: String {
    get {_urlHost ?? String()}
    set {_urlHost = newValue}
  }
  /// Returns true if `urlHost` has been explicitly set.
  public var hasURLHost: Bool {self._urlHost != nil}
  /// Clears the value of `urlHost`. Subsequent reads from it will return its default value.
  public mutating func clearURLHost() {self._urlHost = nil}

  public var urlPath: String {
    get {_urlPath ?? String()}
    set {_urlPath = newValue}
  }
  /// Returns true if `urlPath` has been explicitly set.
  public var hasURLPath: Bool {self._urlPath != nil}
  /// Clears the value of `urlPath`. Subsequent reads from it will return its default value.
  public mutating func clearURLPath() {self._urlPath = nil}

  public var useHTTPS: Bool {
    get {_useHTTPS ?? false}
    set {_useHTTPS = newValue}
  }
  /// Returns true if `useHTTPS` has been explicitly set.
  public var hasUseHTTPS: Bool {self._useHTTPS != nil}
  /// Clears the value of `useHTTPS`. Subsequent reads from it will return its default value.
  public mutating func clearUseHTTPS() {self._useHTTPS = nil}

  public var httpMethod: Int32 {
    get {_httpMethod ?? 0}
    set {_httpMethod = newValue}
  }
  /// Returns true if `httpMethod` has been explicitly set.
  public var hasHTTPMethod: Bool {self._httpMethod != nil}
  /// Clears the value of `httpMethod`. Subsequent reads from it will return its default value.
  public mutating func clearHTTPMethod() {self._httpMethod = nil}

  public var requestHeaders: [PlaydenCloud_ClientCloudFileUploadBlockDetails.HTTPHeaders] = []

  public var blockOffset: UInt64 {
    get {_blockOffset ?? 0}
    set {_blockOffset = newValue}
  }
  /// Returns true if `blockOffset` has been explicitly set.
  public var hasBlockOffset: Bool {self._blockOffset != nil}
  /// Clears the value of `blockOffset`. Subsequent reads from it will return its default value.
  public mutating func clearBlockOffset() {self._blockOffset = nil}

  public var blockLength: UInt32 {
    get {_blockLength ?? 0}
    set {_blockLength = newValue}
  }
  /// Returns true if `blockLength` has been explicitly set.
  public var hasBlockLength: Bool {self._blockLength != nil}
  /// Clears the value of `blockLength`. Subsequent reads from it will return its default value.
  public mutating func clearBlockLength() {self._blockLength = nil}

  public var explicitBodyData: Data {
    get {_explicitBodyData ?? Data()}
    set {_explicitBodyData = newValue}
  }
  /// Returns true if `explicitBodyData` has been explicitly set.
  public var hasExplicitBodyData: Bool {self._explicitBodyData != nil}
  /// Clears the value of `explicitBodyData`. Subsequent reads from it will return its default value.
  public mutating func clearExplicitBodyData() {self._explicitBodyData = nil}

  public var mayParallelize: Bool {
    get {_mayParallelize ?? false}
    set {_mayParallelize = newValue}
  }
  /// Returns true if `mayParallelize` has been explicitly set.
  public var hasMayParallelize: Bool {self._mayParallelize != nil}
  /// Clears the value of `mayParallelize`. Subsequent reads from it will return its default value.
  public mutating func clearMayParallelize() {self._mayParallelize = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated struct HTTPHeaders: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var name: String {
      get {_name ?? String()}
      set {_name = newValue}
    }
    /// Returns true if `name` has been explicitly set.
    public var hasName: Bool {self._name != nil}
    /// Clears the value of `name`. Subsequent reads from it will return its default value.
    public mutating func clearName() {self._name = nil}

    public var value: String {
      get {_value ?? String()}
      set {_value = newValue}
    }
    /// Returns true if `value` has been explicitly set.
    public var hasValue: Bool {self._value != nil}
    /// Clears the value of `value`. Subsequent reads from it will return its default value.
    public mutating func clearValue() {self._value = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _name: String? = nil
    fileprivate var _value: String? = nil
  }

  public init() {}

  fileprivate var _urlHost: String? = nil
  fileprivate var _urlPath: String? = nil
  fileprivate var _useHTTPS: Bool? = nil
  fileprivate var _httpMethod: Int32? = nil
  fileprivate var _blockOffset: UInt64? = nil
  fileprivate var _blockLength: UInt32? = nil
  fileprivate var _explicitBodyData: Data? = nil
  fileprivate var _mayParallelize: Bool? = nil
}

public nonisolated struct PlaydenCloud_CCloud_ClientBeginFileUpload_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var encryptFile: Bool {
    get {_encryptFile ?? false}
    set {_encryptFile = newValue}
  }
  /// Returns true if `encryptFile` has been explicitly set.
  public var hasEncryptFile: Bool {self._encryptFile != nil}
  /// Clears the value of `encryptFile`. Subsequent reads from it will return its default value.
  public mutating func clearEncryptFile() {self._encryptFile = nil}

  public var blockRequests: [PlaydenCloud_ClientCloudFileUploadBlockDetails] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _encryptFile: Bool? = nil
}

public nonisolated struct PlaydenCloud_CCloud_ClientCommitFileUpload_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var transferSucceeded: Bool {
    get {_transferSucceeded ?? false}
    set {_transferSucceeded = newValue}
  }
  /// Returns true if `transferSucceeded` has been explicitly set.
  public var hasTransferSucceeded: Bool {self._transferSucceeded != nil}
  /// Clears the value of `transferSucceeded`. Subsequent reads from it will return its default value.
  public mutating func clearTransferSucceeded() {self._transferSucceeded = nil}

  public var appid: UInt32 {
    get {_appid ?? 0}
    set {_appid = newValue}
  }
  /// Returns true if `appid` has been explicitly set.
  public var hasAppid: Bool {self._appid != nil}
  /// Clears the value of `appid`. Subsequent reads from it will return its default value.
  public mutating func clearAppid() {self._appid = nil}

  public var fileSha: Data {
    get {_fileSha ?? Data()}
    set {_fileSha = newValue}
  }
  /// Returns true if `fileSha` has been explicitly set.
  public var hasFileSha: Bool {self._fileSha != nil}
  /// Clears the value of `fileSha`. Subsequent reads from it will return its default value.
  public mutating func clearFileSha() {self._fileSha = nil}

  public var filename: String {
    get {_filename ?? String()}
    set {_filename = newValue}
  }
  /// Returns true if `filename` has been explicitly set.
  public var hasFilename: Bool {self._filename != nil}
  /// Clears the value of `filename`. Subsequent reads from it will return its default value.
  public mutating func clearFilename() {self._filename = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _transferSucceeded: Bool? = nil
  fileprivate var _appid: UInt32? = nil
  fileprivate var _fileSha: Data? = nil
  fileprivate var _filename: String? = nil
}

public nonisolated struct PlaydenCloud_CCloud_ClientCommitFileUpload_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var fileCommitted: Bool {
    get {_fileCommitted ?? false}
    set {_fileCommitted = newValue}
  }
  /// Returns true if `fileCommitted` has been explicitly set.
  public var hasFileCommitted: Bool {self._fileCommitted != nil}
  /// Clears the value of `fileCommitted`. Subsequent reads from it will return its default value.
  public mutating func clearFileCommitted() {self._fileCommitted = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _fileCommitted: Bool? = nil
}

public nonisolated struct PlaydenCloud_CCloud_ClientDeleteFile_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var appid: UInt32 {
    get {_appid ?? 0}
    set {_appid = newValue}
  }
  /// Returns true if `appid` has been explicitly set.
  public var hasAppid: Bool {self._appid != nil}
  /// Clears the value of `appid`. Subsequent reads from it will return its default value.
  public mutating func clearAppid() {self._appid = nil}

  public var filename: String {
    get {_filename ?? String()}
    set {_filename = newValue}
  }
  /// Returns true if `filename` has been explicitly set.
  public var hasFilename: Bool {self._filename != nil}
  /// Clears the value of `filename`. Subsequent reads from it will return its default value.
  public mutating func clearFilename() {self._filename = nil}

  public var isExplicitDelete: Bool {
    get {_isExplicitDelete ?? false}
    set {_isExplicitDelete = newValue}
  }
  /// Returns true if `isExplicitDelete` has been explicitly set.
  public var hasIsExplicitDelete: Bool {self._isExplicitDelete != nil}
  /// Clears the value of `isExplicitDelete`. Subsequent reads from it will return its default value.
  public mutating func clearIsExplicitDelete() {self._isExplicitDelete = nil}

  public var uploadBatchID: UInt64 {
    get {_uploadBatchID ?? 0}
    set {_uploadBatchID = newValue}
  }
  /// Returns true if `uploadBatchID` has been explicitly set.
  public var hasUploadBatchID: Bool {self._uploadBatchID != nil}
  /// Clears the value of `uploadBatchID`. Subsequent reads from it will return its default value.
  public mutating func clearUploadBatchID() {self._uploadBatchID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _appid: UInt32? = nil
  fileprivate var _filename: String? = nil
  fileprivate var _isExplicitDelete: Bool? = nil
  fileprivate var _uploadBatchID: UInt64? = nil
}

public nonisolated struct PlaydenCloud_CCloud_ClientDeleteFile_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "PlaydenCloud"

nonisolated extension PlaydenCloud_CCloud_BeginAppUploadBatch_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_BeginAppUploadBatch_Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}appid\0\u{3}machine_name\0\u{3}files_to_upload\0\u{3}files_to_delete\0\u{3}client_id\0\u{3}app_build_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._appid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._machineName) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.filesToUpload) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.filesToDelete) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self._clientID) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self._appBuildID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._appid {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._machineName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    if !self.filesToUpload.isEmpty {
      try visitor.visitRepeatedStringField(value: self.filesToUpload, fieldNumber: 3)
    }
    if !self.filesToDelete.isEmpty {
      try visitor.visitRepeatedStringField(value: self.filesToDelete, fieldNumber: 4)
    }
    try { if let v = self._clientID {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._appBuildID {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_BeginAppUploadBatch_Request, rhs: PlaydenCloud_CCloud_BeginAppUploadBatch_Request) -> Bool {
    if lhs._appid != rhs._appid {return false}
    if lhs._machineName != rhs._machineName {return false}
    if lhs.filesToUpload != rhs.filesToUpload {return false}
    if lhs.filesToDelete != rhs.filesToDelete {return false}
    if lhs._clientID != rhs._clientID {return false}
    if lhs._appBuildID != rhs._appBuildID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_BeginAppUploadBatch_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_BeginAppUploadBatch_Response"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_id\0\u{4}\u{3}app_change_number\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self._batchID) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self._appChangeNumber) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._batchID {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._appChangeNumber {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_BeginAppUploadBatch_Response, rhs: PlaydenCloud_CCloud_BeginAppUploadBatch_Response) -> Bool {
    if lhs._batchID != rhs._batchID {return false}
    if lhs._appChangeNumber != rhs._appChangeNumber {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_CompleteAppUploadBatch_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_CompleteAppUploadBatch_Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}appid\0\u{3}batch_id\0\u{3}batch_eresult\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._appid) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self._batchID) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self._batchEresult) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._appid {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._batchID {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._batchEresult {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_CompleteAppUploadBatch_Request, rhs: PlaydenCloud_CCloud_CompleteAppUploadBatch_Request) -> Bool {
    if lhs._appid != rhs._appid {return false}
    if lhs._batchID != rhs._batchID {return false}
    if lhs._batchEresult != rhs._batchEresult {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_CompleteAppUploadBatch_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_CompleteAppUploadBatch_Response"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_CompleteAppUploadBatch_Response, rhs: PlaydenCloud_CCloud_CompleteAppUploadBatch_Response) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_ClientBeginFileUpload_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_ClientBeginFileUpload_Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}appid\0\u{3}file_size\0\u{3}raw_file_size\0\u{3}file_sha\0\u{3}time_stamp\0\u{1}filename\0\u{3}platforms_to_sync\0\u{4}\u{2}cell_id\0\u{3}can_encrypt\0\u{3}is_shared_file\0\u{3}deprecated_realm\0\u{3}upload_batch_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._appid) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._fileSize) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self._rawFileSize) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self._fileSha) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self._timeStamp) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._filename) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self._platformsToSync) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self._cellID) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self._canEncrypt) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self._isSharedFile) }()
      case 12: try { try decoder.decodeSingularUInt32Field(value: &self._deprecatedRealm) }()
      case 13: try { try decoder.decodeSingularUInt64Field(value: &self._uploadBatchID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._appid {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._fileSize {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._rawFileSize {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._fileSha {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._timeStamp {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._filename {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._platformsToSync {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._cellID {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._canEncrypt {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._isSharedFile {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._deprecatedRealm {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 12)
    } }()
    try { if let v = self._uploadBatchID {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 13)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_ClientBeginFileUpload_Request, rhs: PlaydenCloud_CCloud_ClientBeginFileUpload_Request) -> Bool {
    if lhs._appid != rhs._appid {return false}
    if lhs._fileSize != rhs._fileSize {return false}
    if lhs._rawFileSize != rhs._rawFileSize {return false}
    if lhs._fileSha != rhs._fileSha {return false}
    if lhs._timeStamp != rhs._timeStamp {return false}
    if lhs._filename != rhs._filename {return false}
    if lhs._platformsToSync != rhs._platformsToSync {return false}
    if lhs._cellID != rhs._cellID {return false}
    if lhs._canEncrypt != rhs._canEncrypt {return false}
    if lhs._isSharedFile != rhs._isSharedFile {return false}
    if lhs._deprecatedRealm != rhs._deprecatedRealm {return false}
    if lhs._uploadBatchID != rhs._uploadBatchID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_ClientCloudFileUploadBlockDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClientCloudFileUploadBlockDetails"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}url_host\0\u{3}url_path\0\u{3}use_https\0\u{3}http_method\0\u{3}request_headers\0\u{3}block_offset\0\u{3}block_length\0\u{3}explicit_body_data\0\u{3}may_parallelize\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._urlHost) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._urlPath) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._useHTTPS) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._httpMethod) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.requestHeaders) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self._blockOffset) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self._blockLength) }()
      case 8: try { try decoder.decodeSingularBytesField(value: &self._explicitBodyData) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self._mayParallelize) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._urlHost {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._urlPath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._useHTTPS {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._httpMethod {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    if !self.requestHeaders.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.requestHeaders, fieldNumber: 5)
    }
    try { if let v = self._blockOffset {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._blockLength {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._explicitBodyData {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._mayParallelize {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_ClientCloudFileUploadBlockDetails, rhs: PlaydenCloud_ClientCloudFileUploadBlockDetails) -> Bool {
    if lhs._urlHost != rhs._urlHost {return false}
    if lhs._urlPath != rhs._urlPath {return false}
    if lhs._useHTTPS != rhs._useHTTPS {return false}
    if lhs._httpMethod != rhs._httpMethod {return false}
    if lhs.requestHeaders != rhs.requestHeaders {return false}
    if lhs._blockOffset != rhs._blockOffset {return false}
    if lhs._blockLength != rhs._blockLength {return false}
    if lhs._explicitBodyData != rhs._explicitBodyData {return false}
    if lhs._mayParallelize != rhs._mayParallelize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_ClientCloudFileUploadBlockDetails.HTTPHeaders: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = PlaydenCloud_ClientCloudFileUploadBlockDetails.protoMessageName + ".HTTPHeaders"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}value\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._value) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._value {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_ClientCloudFileUploadBlockDetails.HTTPHeaders, rhs: PlaydenCloud_ClientCloudFileUploadBlockDetails.HTTPHeaders) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._value != rhs._value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_ClientBeginFileUpload_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_ClientBeginFileUpload_Response"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}encrypt_file\0\u{3}block_requests\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._encryptFile) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.blockRequests) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._encryptFile {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    if !self.blockRequests.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.blockRequests, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_ClientBeginFileUpload_Response, rhs: PlaydenCloud_CCloud_ClientBeginFileUpload_Response) -> Bool {
    if lhs._encryptFile != rhs._encryptFile {return false}
    if lhs.blockRequests != rhs.blockRequests {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_ClientCommitFileUpload_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_ClientCommitFileUpload_Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}transfer_succeeded\0\u{1}appid\0\u{3}file_sha\0\u{1}filename\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._transferSucceeded) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._appid) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self._fileSha) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._filename) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._transferSucceeded {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._appid {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._fileSha {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._filename {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_ClientCommitFileUpload_Request, rhs: PlaydenCloud_CCloud_ClientCommitFileUpload_Request) -> Bool {
    if lhs._transferSucceeded != rhs._transferSucceeded {return false}
    if lhs._appid != rhs._appid {return false}
    if lhs._fileSha != rhs._fileSha {return false}
    if lhs._filename != rhs._filename {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_ClientCommitFileUpload_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_ClientCommitFileUpload_Response"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}file_committed\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._fileCommitted) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._fileCommitted {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_ClientCommitFileUpload_Response, rhs: PlaydenCloud_CCloud_ClientCommitFileUpload_Response) -> Bool {
    if lhs._fileCommitted != rhs._fileCommitted {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_ClientDeleteFile_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_ClientDeleteFile_Request"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}appid\0\u{1}filename\0\u{3}is_explicit_delete\0\u{3}upload_batch_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._appid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._filename) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._isExplicitDelete) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self._uploadBatchID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._appid {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._filename {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._isExplicitDelete {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._uploadBatchID {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_ClientDeleteFile_Request, rhs: PlaydenCloud_CCloud_ClientDeleteFile_Request) -> Bool {
    if lhs._appid != rhs._appid {return false}
    if lhs._filename != rhs._filename {return false}
    if lhs._isExplicitDelete != rhs._isExplicitDelete {return false}
    if lhs._uploadBatchID != rhs._uploadBatchID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PlaydenCloud_CCloud_ClientDeleteFile_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CCloud_ClientDeleteFile_Response"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PlaydenCloud_CCloud_ClientDeleteFile_Response, rhs: PlaydenCloud_CCloud_ClientDeleteFile_Response) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
